export const CREATE_ORDER_START = 'CREATE_ORDER_START';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET';

export const GET_ORDER_START = 'GET_ORDER_START';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL';

export const ORDER_PAY_START = 'ORDER_PAY_START';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_DILIVERD_START = 'ORDER_DILIVERD_START';
export const ORDER_DILIVERD_SUCCESS = 'ORDER_DILIVERD_SUCCESS';
export const ORDER_DILIVERD_FAIL = 'ORDER_DILIVERD_FAIL';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';

export const AUTH_ORDER_FETCH_START = 'AUTH_ORDER_FETCH_START';
export const AUTH_ORDER_FETCH_SUCCESS = 'AUTH_ORDER_FETCH_SUCCESS';
export const AUTH_ORDER_FETCH_FAIL = 'AUTH_ORDER_FETCH_FAIL';

export const ORDERLIST_FETCH_START = 'ORDERLIST_FETCH_START';
export const ORDERLIST_FETCH_SUCCESS = 'ORDERLIST_FETCH_SUCCESS';
export const ORDERLIST_FETCH_FAIL = 'ORDERLIST_FETCH_FAIL';
