export const PRODUCTLIST_FETCH_START = "PRODUCTLIST_FETCH_START";
export const PRODUCTLIST_FETCH_SUCCESS = "PRODUCTLIST_FETCH_SUCCESS";
export const PRODUCTLIST_FETCH_ERROR = "PRODUCTLIST_FETCH_ERROR";

export const PRODUCT_FETCH_START = "PRODUCT_FETCH_START";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAIL = "PRODUCT_FETCH_FAIL";

export const PRODUCTREVIEW_FETCH_START = "PRODUCTREVIEW_FETCH_START";
export const PRODUCTREVIEW_FETCH_SUCCESS = "PRODUCTREVIEW_FETCH_SUCCESS";
export const PRODUCTREVIEW_FETCH_FAIL = "PRODUCTREVIEW_FETCH_FAIL";

export const CREATE_REVIEW_START = "CREATE_REVIEW_START";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";
