export const PRODUCTLIST_FETCH_START = "PRODUCTLIST_FETCH_START";
export const PRODUCTLIST_FETCH_SUCCESS = "PRODUCTLIST_FETCH_SUCCESS";
export const PRODUCTLIST_FETCH_ERROR = "PRODUCTLIST_FETCH_ERROR";

export const PRODUCT_FETCH_START = "PRODUCT_FETCH_START";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAIL = "PRODUCT_FETCH_FAIL";
